buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:1.2-SNAPSHOT'
    }
}

apply plugin: 'forge'

group = 'ru.npp.extension'
version = '1.0.0'
archivesBaseName = 'npp-extension'

minecraft {
    version = '1.7.10-10.13.4.1614-1.7.10'
    runDir = 'run'
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
    options.encoding = 'UTF-8'
}
